---
title: "Portfolio 1"
name: "Cat Seitz"
date: "1.21.2023"
data: "Distractor Suppression Pilot Study"
---

> The projects should be numbered consecutively (i.e., in the order in which you began them), and should include for each project a description of the goal, the product (computer program, hand graph, computer graph, etc.), the data, and some interpretation. Reports must be reproducible and of high quality in terms of writing, grammar, presentation, etc.

```{r load-packages, message=FALSE}
library(tidyverse) 
library(tidyr)
```



```{r import data}

pilot <- read_csv("p01/data/pilot_final.csv", show_col_types = FALSE)
  
```


```{r}
# Create a barplot of the number of fish encounters by species
ggplot(data = fish_encounters, aes(x = species, y = count)) +
  geom_bar(stat = "identity") +
  labs(x = "Species", y = "Number of Fish Encounters")
  
```


```{r}
# Create a barplot of the number of fish encounters by species
ggplot(data = fish_encounters, aes(x = species, y = count)) +
  geom_bar(stat = "identity") +
  labs(x = "Species", y = "Number of Fish Encounters")
  
```

