---
title: "Superpower Demo"
output: html_notebook
---

Load in the Superpower Package

```{r load-packages}
library(Superpower)
library(data.table)
library(emmeans)
library(tidyverse) 
library(tidyr)
```

Instructions from the package are here: https://cran.r-project.org/web/packages/Superpower/vignettes/intro_to_superpower.html#anova_design-function

Set up the design

```{r run design}
young_design <- ANOVA_design(design = "3w",
                             n=21,
                             mu = c(780.8287, 861.8318, 917.4635),
                             sd = 152,
                             r <- c(0.9603,0.9479,0.9434),
                             labelnames = c("DistractorPresence", "DistAbsent", "HighProb", "LowProb")
                             )

```


Plot power as a function of sample size

```{r plot}
plot_power(young_design, min_n=5, max_n = 100, desired_power=80, exact2 = TRUE)

```

Run a power simulation based on the N defined above.

```{r}
results=ANOVA_power(design_result = young_design,alpha_level = 0.001, nsims = 10000, seed=1234,)

```






Run correlations:

Distractor location response times

```{r get-relavant-info}

pilot <- read_csv("p01/p01/data/pilot_final.csv", show_col_types = FALSE)

pilot$relative_hp_dist[pilot$relative_hp_dist == 10] <- "no_dist"
pilot$relative_hp_dist[pilot$relative_hp_dist == 0] <- "dist_0"
pilot$relative_hp_dist[pilot$relative_hp_dist == 1] <- "dist_1"
pilot$relative_hp_dist[pilot$relative_hp_dist == 2] <- "dist_2"
pilot$relative_hp_dist[pilot$relative_hp_dist == 3] <- "dist_3"

pilot$RT <- pilot$RT *1000

block_num <- rep(c(1,2,3,4,5,6,7,8), each=60, times=21)
pilot <- cbind(pilot, block_num)

xsize <- c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 
             25, 30, 35, 50, 100)
stds <- c(1.458, 1.68, 1.841, 1.961, 2.05, 2.12, 2.173, 
            2.22, 2.246, 2.274, 2.31, 2.326, 2.391, 2.41, 2.4305, 
            2.45, 2.48, 2.5)

trimmed <- pilot[pilot$acc==100, ] %>% group_by(ID, relative_hp_dist) %>%
           mutate(sdc = ifelse(length(RT)>=100,2.5,approx(xsize,stds,xout=length(RT))$y), avg = mean(RT), stdev = sd(RT)) %>%
           filter(RT <= sdc*stdev+avg & RT >=avg-(sdc*stdev) & RT >=.200) %>%
           select(ID, relative_hp_dist, RT, block_num) %>%  #keep these columns in the new data frame
           as.data.frame()


statPrep <- trimmed %>% group_by(ID, relative_hp_dist) %>% summarise(measurement=mean(RT)) %>% as.data.frame()
100-(nrow(trimmed)/nrow(pilot[pilot$acc==100, ]))*100

space <- trimmed %>%
  group_by(ID, relative_hp_dist) %>%
  summarize(rts = mean(RT)
            )

space_anova <- setDT(space)
space_anova <- dcast(space_anova,ID~relative_hp_dist,value.var='rts')

space_anova <- space_anova %>%
  mutate(low_prob = (dist_1+dist_2+dist_3)/3)

```

```{r run-correlations}

cor(space_anova$dist_0, space_anova$low_prob)
cor(space_anova$dist_0, space_anova$no_dist)
cor(space_anova$no_dist, space_anova$low_prob)

```

Target Location Response Times

```{r target-stuff}
pilot <- read_csv("p02/pilot_final.csv", show_col_types = FALSE)

pilot$relative_hp_dist[pilot$relative_hp_dist == 10] <- "no_dist"
pilot$relative_hp_dist[pilot$relative_hp_dist == 0] <- "dist_0"
pilot$relative_hp_dist[pilot$relative_hp_dist == 1] <- "dist_1"
pilot$relative_hp_dist[pilot$relative_hp_dist == 2] <- "dist_2"
pilot$relative_hp_dist[pilot$relative_hp_dist == 3] <- "dist_3"
pilot$RT <- pilot$RT *1000

block_num <- rep(c(1,2,3,4,5,6,7,8), each=60, times=21)
pilot <- cbind(pilot, block_num)

pilot <- pilot %>%
  mutate(relative_target=
           case_when(target_loc=="loc1" & high_prob==1 ~ 0,
                     target_loc=="loc2" & high_prob==1 ~ 1,
                     target_loc=="loc3" & high_prob==1 ~ 2,
                     target_loc=="loc4" & high_prob==1 ~ 3,
                     target_loc=="loc5" & high_prob==1 ~ 2,
                     target_loc=="loc6" & high_prob==1 ~ 1,
                     target_loc=="loc1" & high_prob==2 ~ 1,
                     target_loc=="loc2" & high_prob==2 ~ 0,
                     target_loc=="loc3" & high_prob==2 ~ 1,
                     target_loc=="loc4" & high_prob==2 ~ 2,
                     target_loc=="loc5" & high_prob==2 ~ 3,
                     target_loc=="loc6" & high_prob==2 ~ 2,
                     target_loc=="loc1" & high_prob==3 ~ 2,
                     target_loc=="loc2" & high_prob==3 ~ 1,
                     target_loc=="loc3" & high_prob==3 ~ 0,
                     target_loc=="loc4" & high_prob==3 ~ 1,
                     target_loc=="loc5" & high_prob==3 ~ 2,
                     target_loc=="loc6" & high_prob==3 ~ 3,
                     target_loc=="loc1" & high_prob==4 ~ 3,
                     target_loc=="loc2" & high_prob==4 ~ 2,
                     target_loc=="loc3" & high_prob==4 ~ 1,
                     target_loc=="loc4" & high_prob==4 ~ 0,
                     target_loc=="loc5" & high_prob==4 ~ 1,
                     target_loc=="loc6" & high_prob==4 ~ 2,
                     target_loc=="loc1" & high_prob==5 ~ 2,
                     target_loc=="loc2" & high_prob==5 ~ 3,
                     target_loc=="loc3" & high_prob==5 ~ 2,
                     target_loc=="loc4" & high_prob==5 ~ 1,
                     target_loc=="loc5" & high_prob==5 ~ 0,
                     target_loc=="loc6" & high_prob==5 ~ 1,
                     target_loc=="loc1" & high_prob==6 ~ 1,
                     target_loc=="loc2" & high_prob==6 ~ 2,
                     target_loc=="loc3" & high_prob==6 ~ 3,
                     target_loc=="loc4" & high_prob==6 ~ 2,
                     target_loc=="loc5" & high_prob==6 ~ 1,
                     target_loc=="loc6" & high_prob==6 ~ 0,))

pilot$relative_target[pilot$relative_target == 0] <- "high_prob"
pilot$relative_target[pilot$relative_target == 1] <- "lp_1"
pilot$relative_target[pilot$relative_target == 2] <- "lp_2"
pilot$relative_target[pilot$relative_target == 3] <- "lp_3"

add_this<- pilot[pilot$acc==100,]

trimmed <- add_this[add_this$relative_hp_dist=="no_dist",] %>% 
  group_by(ID, relative_target) %>%
           mutate(sdc = ifelse(length(RT)>=100,2.5,approx(xsize,stds,xout=length(RT))$y), avg = mean(RT), stdev = sd(RT)) %>%
           filter(RT <= sdc*stdev+avg & RT >=avg-(sdc*stdev) & RT >=.200) %>%
           select(ID, relative_hp_dist, RT, block_num, relative_target) %>%
           as.data.frame()


statPrep <- trimmed %>% group_by(ID, relative_target) %>% summarise(measurement=mean(RT)) %>% as.data.frame()
100-(nrow(trimmed)/nrow(add_this[add_this$relative_hp_dist=="no_dist",]))*100

space <- trimmed %>%
  subset(relative_hp_dist=="no_dist")%>%
  group_by(ID, relative_target) %>%
  summarize(rts = mean(RT),
            )

space_anova <- setDT(space)
space_anova <- dcast(space_anova,ID~relative_target,value.var='rts')

space_anova <- space_anova %>%
  mutate(low_prob = (lp_1+lp_2+lp_3)/3)

```

```{r target-corr}

cor(space_anova$high_prob, space_anova$low_prob)

```

```{r plot target rts}
young_design <- ANOVA_design(design = "2w",
                             n=21,
                             mu = c(796.9622, 777.3374),
                             sd = 120,
                             r <- c(0.9191),
                             labelnames = c("TargetLocation", "HighProb", "LowProb")
                             )

```

```{r plot-target-rt}
plot_power(young_design, min_n=5, max_n = 100, desired_power=80, exact2 = TRUE)

```




Distractor and Target Accuracy


```{r create_accuracy_df}




pilot_distacc <- pilot %>%
  group_by(relative_hp_dist) %>%
  summarize(accuracy = mean(acc),
            sd_rt=sd(acc),
            n_rt=21,
            se=sd_rt/sqrt(n_rt),
            upper_limit=accuracy+se,
            lower_limit=accuracy-se
            )
pilot_targacc <- pilot %>%
  subset(relative_hp_dist=="no_dist")%>%
  group_by(relative_target) %>%
  summarize(accuracy = mean(acc),
            sd_rt=sd(acc),
            n_rt=21,
            se=sd_rt/sqrt(n_rt),
            upper_limit=accuracy+se,
            lower_limit=accuracy-se
            )

pilot_dist <- pilot %>%
  group_by(ID, relative_hp_dist) %>%
  summarize(accuracy = mean(acc)
            )


pilot_targ <- pilot %>%
  subset(relative_hp_dist=="no_dist")%>%
  group_by(ID, relative_target) %>%
  summarize(accuracy = mean(acc)
            )
dist_t <- setDT(pilot_dist)
dist_t <- dcast(pilot_dist,ID~relative_hp_dist,value.var='accuracy')

dist_t <- dist_t %>%
  mutate(low_prob = (dist_1+dist_2+dist_3)/3)

targ_t <- setDT(pilot_targ)
targ_t <- dcast(pilot_targ,ID~relative_target,value.var='accuracy')

targ_t <- targ_t %>%
  mutate(low_prob = (lp_1+lp_2+lp_3)/3)

```

```{r corr-acc}

cor(dist_t$dist_0, dist_t$low_prob)
cor(dist_t$dist_0, dist_t$no_dist)
cor(dist_t$no_dist, dist_t$low_prob)

cor(targ_t$high_prob, targ_t$low_prob)

```


```{r plot target acc}
targacc_design <- ANOVA_design(design = "2w",
                             n=21,
                             mu = c(97.38095, 98.0754),
                             sd = 2.79,
                             r <- c(0.48269),
                             labelnames = c("TargetLocation", "HighProb", "LowProb")
                             )

```

```{r plot-target-acc}
plot_power(targacc_design, min_n=5, max_n = 100, desired_power=80, exact2 = TRUE)

```


```{r plot dist acc}
distacc_design <- ANOVA_design(design = "3w",
                             n=21,
                             mu = c(97.93651, 96.12528, 94.7586),
                             sd = 4,
                             r <- c(0.75187, 0.60643, 0.82988),
                             labelnames = c("DistractorLocation", "Absent", "HighProb", "LowProb")
                             )

```

```{r plot-dist-acc}
plot_power(distacc_design, min_n=5, max_n = 100, desired_power=80, exact2 = TRUE)

```
