<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 7</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 7</h1>
<h4 class="date">03.25.2023</h4>

</div>


<p>The goal of this portfolio is to examine part of my thesis data. To
recap, my thesis is examining distractor suppression in children and
adults. Participants are shown a distractor in a location more
frequently than other locations in a visual search array. Based on
previous studies, we would expect adults to suppress their tendency to
attend to a salient distractor in a high-probability location, but we
were unsure when in development children develop this ability.</p>
<pre class="r"><code>library(tidyverse) 
library(tidyr)
library(rstatix)
library(data.table)
library(afex)
library(emmeans)
library(psych)
library(ggprism)
library(patchwork)
library(magrittr)
library(cowplot)</code></pre>
<p>I put all the messy loading in of different data sets and adding in
important columns to an R script instead of having it here.</p>
<p>Load in change detection task data (visual working memory capacity
measurements)</p>
<pre class="r"><code>cdt &lt;- read_csv(&quot;RawDataCDT.csv&quot;, show_col_types = FALSE)</code></pre>
<div id="data-management-of-change-detection-task-data"
class="section level3">
<h3>Data Management of Change Detection Task Data</h3>
<p>Identify cases of hits, false alarms, correct rejections, and misses
depending on if the trial was accurate and if their was a change.</p>
<pre class="r"><code>cdt &lt;- cdt %&gt;%
  mutate(outcome=
           case_when(Accurate==1 &amp; Change==1 ~ &quot;hit&quot;,
                     Accurate==1 &amp; Change==0 ~ &quot;cor_rej&quot;,
                     Accurate==0 &amp; Change==1 ~ &quot;miss&quot;,
                     Accurate==0 &amp; Change==0 ~ &quot;f_alarm&quot;,
           ))</code></pre>
<p>Group by the ppt ID and the set size to determine how many instances
of each possible outcome there were.</p>
<pre class="r"><code>cdt&lt;-cdt%&gt;%
  group_by(SubID, SetSize)%&gt;%
  count(outcome)</code></pre>
<p>Reformat to have column for each outcome</p>
<pre class="r"><code>cdt1 &lt;- setDT(cdt)
cdt1 &lt;- dcast(cdt1,SubID+SetSize~outcome,value.var=&#39;n&#39;)</code></pre>
<p>Get rid of participants without enough data (I checked for this
manual and filtered those IDs) and fill na values with zeros.</p>
<pre class="r"><code>cdt1&lt;- cdt1%&gt;%
  filter(SubID != 55, SubID != 76)

cdt1[is.na(cdt1)] &lt;- 0

cdt1 &lt;- cdt1 %&gt;% 
  select(-c(&quot;NA&quot;))</code></pre>
<p>Calculate the hit rate.</p>
<pre class="r"><code>cdt1&lt;-cdt1 %&gt;%
  mutate(hit_rate = hit/(hit+miss))</code></pre>
<p>Calculate the false alarm rate.</p>
<pre class="r"><code>cdt1&lt;-cdt1 %&gt;%
  mutate(fa_rate = f_alarm/(f_alarm+cor_rej))</code></pre>
<p>Calculate the capacity for each set size</p>
<pre class="r"><code>cdt1&lt;-cdt1 %&gt;%
  mutate(K = SetSize*(hit_rate-fa_rate))</code></pre>
<p>Need to make a new data frame with the average capacity per
participant.</p>
<pre class="r"><code>capacity &lt;- cdt1 %&gt;%
  group_by(SubID) %&gt;%
  summarize(avg_k = mean(K))</code></pre>
<p>From this, we find out that ppt 104 was pressing keys for the tasks
backwards. Delete them?</p>
<pre class="r"><code>capacity &lt;- capacity %&gt;%
  filter(SubID != 104)</code></pre>
</div>
<div id="trim-the-rt-data" class="section level3">
<h3>Trim the RT Data</h3>
<pre class="r"><code>aggregate(rt ~ acc, data = adults, FUN = mean)</code></pre>
<pre><code>##   acc       rt
## 1   0 1036.116
## 2   1 1126.754</code></pre>
<pre class="r"><code>aggregate(rt ~ acc, data = adults, FUN = sd)</code></pre>
<pre><code>##   acc       rt
## 1   0 610.4570
## 2   1 668.7103</code></pre>
<pre class="r"><code>aggregate(rt ~ acc, data = kids12, FUN = mean)</code></pre>
<pre><code>##   acc        rt
## 1   0  851.4179
## 2   1 2130.8040</code></pre>
<pre class="r"><code>aggregate(rt ~ acc, data = kids12, FUN = sd)</code></pre>
<pre><code>##   acc       rt
## 1   0 1357.789
## 2   1 2727.995</code></pre>
<pre class="r"><code>aggregate(rt ~ acc, data = kids6, FUN = mean)</code></pre>
<pre><code>##   acc        rt
## 1   0  201.1421
## 2   1 3112.2998</code></pre>
<pre class="r"><code>aggregate(rt ~ acc, data = kids6, FUN = sd)</code></pre>
<pre><code>##   acc        rt
## 1   0  951.0326
## 2   1 3594.9864</code></pre>
<p>Define trimming criteria according to Van Selst and Jolicoeur
1994.</p>
<pre class="r"><code>xsize &lt;- c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 
             25, 30, 35, 50, 100)
stds &lt;- c(1.458, 1.68, 1.841, 1.961, 2.05, 2.12, 2.173, 
            2.22, 2.246, 2.274, 2.31, 2.326, 2.391, 2.41, 2.4305, 
            2.45, 2.48, 2.5)</code></pre>
<p>Trim the data and compute the percent trimmed</p>
<pre class="r"><code>trimmedA &lt;- adults[adults$acc==1, ] %&gt;% group_by(id, relative_hp_dist) %&gt;%
           mutate(sdc = ifelse(length(rt)&gt;=100,2.5,approx(xsize,stds,xout=length(rt))$y), avg = mean(rt), stdev = sd(rt)) %&gt;%
           filter(rt &lt;= sdc*stdev+avg &amp; rt &gt;=avg-(sdc*stdev) &amp; rt &gt;=200 &amp; rt&lt;=2500) %&gt;% #exact upper limit =2464.175
           select(id, age, relative_hp_dist, rt, block_num) %&gt;%  #keep these columns in the new data frame
           as.data.frame()


statPrep &lt;- trimmedA %&gt;% group_by(id, relative_hp_dist) %&gt;% summarise(measurement=mean(rt)) %&gt;% as.data.frame()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre class="r"><code>100-(nrow(trimmedA)/nrow(adults[adults$acc==1, ]))*100</code></pre>
<pre><code>## [1] 5.100756</code></pre>
<p>5.10% of trials were trimmed from the adult data set.</p>
<pre class="r"><code>trimmedC12 &lt;- kids12[kids12$acc==1, ] %&gt;% group_by(id, relative_hp_dist) %&gt;%
           mutate(sdc = ifelse(length(rt)&gt;=100,2.5,approx(xsize,stds,xout=length(rt))$y), avg = mean(rt), stdev = sd(rt)) %&gt;%
           filter(rt &lt;= sdc*stdev+avg &amp; rt &gt;=avg-(sdc*stdev) &amp; rt &gt;=200 &amp; rt&lt;=7590) %&gt;%  #exact upper limit =7586.794
           select(id, age1, relative_hp_dist, rt, block_num1) %&gt;%  #keep these columns in the new data frame
           as.data.frame()


statPrep &lt;- trimmedC12 %&gt;% group_by(id, relative_hp_dist) %&gt;% summarise(measurement=mean(rt)) %&gt;% as.data.frame()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre class="r"><code>100-(nrow(trimmedC12)/nrow(kids12[kids12$acc==1, ]))*100</code></pre>
<pre><code>## [1] 4.639738</code></pre>
<p>4.64% of trials were trimmed from the older child data set.</p>
<pre class="r"><code>trimmedC6 &lt;- kids6[kids6$acc==1, ] %&gt;% group_by(id, relative_hp_dist) %&gt;%
           mutate(sdc = ifelse(length(rt)&gt;=100,2.5,approx(xsize,stds,xout=length(rt))$y), avg = mean(rt), stdev = sd(rt)) %&gt;%
           filter(rt &lt;= sdc*stdev+avg &amp; rt &gt;=avg-(sdc*stdev) &amp; rt &gt;=200 &amp; rt&lt;=18950) %&gt;% #exact upper limit =18929.79
           select(id, age2, relative_hp_dist, rt, block_num2) %&gt;%  #keep these columns in the new data frame
           as.data.frame()


statPrep &lt;- trimmedC6 %&gt;% group_by(id, relative_hp_dist) %&gt;% summarise(measurement=mean(rt)) %&gt;% as.data.frame()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre class="r"><code>100-(nrow(trimmedC6)/nrow(kids6[kids6$acc==1, ]))*100</code></pre>
<pre><code>## [1] 5.181347</code></pre>
<p>Make the column names for block number the same for children and
adults.</p>
<pre class="r"><code>trimmedC12&lt;- trimmedC12 %&gt;%
  rename(
    block_num=block_num1,
    age=age1
  )

trimmedC6&lt;- trimmedC6 %&gt;%
  rename(
    block_num=block_num2,
    age=age2
  )</code></pre>
<p>Bind adults and older children together in the same dataframe.</p>
<pre class="r"><code>all_data &lt;- rbind(trimmedA, trimmedC12)</code></pre>
<p>Find mean response times depending on block number and distractor
location.</p>
<pre class="r"><code>space_block &lt;- all_data %&gt;%
  group_by(id, age, block_num, relative_hp_dist) %&gt;%
  summarize(rts = mean(rt)
  )</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;, &#39;age&#39;,
## &#39;block_num&#39;. You can override using the `.groups` argument.</code></pre>
<p>Transform the df to be shaped differently.</p>
<pre class="r"><code>space_block &lt;- setDT(space_block)
space_block &lt;- dcast(space_block,id+age+block_num~relative_hp_dist,value.var=&#39;rts&#39;)</code></pre>
<p>I added the average rt for the low probability locations and the
difference between the low probability and high probability locations
ignoring n/a values.</p>
<pre class="r"><code>space_block &lt;- space_block %&gt;%
  mutate(low_prob = rowMeans(select(space_block, c(lp_1,lp_2,lp_3)),na.rm=TRUE)) %&gt;%
  mutate(difference = (low_prob-high_prob))</code></pre>
<p>Create a new df for the suppression effect for each ppt.</p>
<pre class="r"><code>supp &lt;- space_block %&gt;%
  group_by(id)%&gt;%
  summarize(effect = mean(difference, na.rm = TRUE))

supp</code></pre>
<pre><code>## # A tibble: 33 × 2
##       id effect
##    &lt;dbl&gt;  &lt;dbl&gt;
##  1    14   95.2
##  2    15   99.7
##  3    16   65.3
##  4    18   51.7
##  5    19   50.3
##  6    20   43.6
##  7    21   83.5
##  8    22  123. 
##  9    23  -84.9
## 10    24  -76.6
## # … with 23 more rows</code></pre>
<p>Get rid of ppts who didn’t complete the CDT.</p>
<pre class="r"><code>supp &lt;- supp %&gt;%
  filter(id != 104, id != 53, id != 54, id != 55, id != 76, id != 26)</code></pre>
</div>
<div id="merge-data-frames-and-correlate" class="section level3">
<h3>Merge Data Frames and correlate?</h3>
<pre class="r"><code>df &lt;- cbind(supp, capacity)

df &lt;- df %&gt;% 
  select(-c(&quot;SubID&quot;))</code></pre>
<pre class="r"><code>cor.test(df$effect, df$avg_k)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df$effect and df$avg_k
## t = 1.1072, df = 25, p-value = 0.2787
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.1784760  0.5509497
## sample estimates:
##       cor 
## 0.2162015</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
