<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 9</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 9</h1>
<h4 class="date">3.21.2023</h4>

</div>


<p>The goal of this portfolio is to examine part of my thesis data. To
recap, my thesis is examining distractor suppression in children and
adults. Participants are shown a distractor in a location more
frequently than other locations in a visual search array. Based on
previous studies, we would expect adults to suppress their attention to
the high-probability location, but we were unsure when in development
children develop this ability.</p>
<pre class="r"><code>library(tidyverse) 
library(tidyr)
library(rstatix)
library(data.table)
library(afex)
library(emmeans)
library(psych)
library(ggprism)
library(patchwork)
library(magrittr)
library(cowplot)</code></pre>
<p>I put all the messy loading in of different data sets and adding in
important columns to an R script instead of having it here.</p>
<div id="trim-the-data" class="section level3">
<h3>Trim the Data</h3>
<p>Define trimming criteria according to Van Selst and Jolicoeur
1994.</p>
<pre class="r"><code>xsize &lt;- c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 
             25, 30, 35, 50, 100)
stds &lt;- c(1.458, 1.68, 1.841, 1.961, 2.05, 2.12, 2.173, 
            2.22, 2.246, 2.274, 2.31, 2.326, 2.391, 2.41, 2.4305, 
            2.45, 2.48, 2.5)</code></pre>
<p>Trim the data and compute the percent trimmed</p>
<pre class="r"><code>trimmedA &lt;- adults[adults$acc==1, ] %&gt;% group_by(id, relative_hp_dist) %&gt;%
           mutate(sdc = ifelse(length(rt)&gt;=100,2.5,approx(xsize,stds,xout=length(rt))$y), avg = mean(rt), stdev = sd(rt)) %&gt;%
           filter(rt &lt;= sdc*stdev+avg &amp; rt &gt;=avg-(sdc*stdev) &amp; rt &gt;=200 &amp; rt&lt;=2500) %&gt;% #exact upper limit =2464.175
           select(id, age, relative_hp_dist, rt, block_num) %&gt;%  #keep these columns in the new data frame
           as.data.frame()


statPrep &lt;- trimmedA %&gt;% group_by(id, relative_hp_dist) %&gt;% summarise(measurement=mean(rt)) %&gt;% as.data.frame()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;. You can override using the `.groups`
## argument.</code></pre>
<pre class="r"><code>100-(nrow(trimmedA)/nrow(adults[adults$acc==1, ]))*100</code></pre>
<pre><code>## [1] 5.100756</code></pre>
<p>5.10% of trials were trimmed from the adult data set.</p>
<pre class="r"><code>trimmedC12 &lt;- kids12[kids12$acc==1, ] %&gt;% group_by(id, relative_hp_dist) %&gt;%
           mutate(sdc = ifelse(length(rt)&gt;=100,2.5,approx(xsize,stds,xout=length(rt))$y), avg = mean(rt), stdev = sd(rt)) %&gt;%
           filter(rt &lt;= sdc*stdev+avg &amp; rt &gt;=avg-(sdc*stdev) &amp; rt &gt;=200 &amp; rt&lt;=7590) %&gt;%  #exact upper limit =7586.794
           select(id, age1, relative_hp_dist, rt, block_num1) %&gt;%  #keep these columns in the new data frame
           as.data.frame()


statPrep &lt;- trimmedC12 %&gt;% group_by(id, relative_hp_dist) %&gt;% summarise(measurement=mean(rt)) %&gt;% as.data.frame()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;. You can override using the `.groups`
## argument.</code></pre>
<pre class="r"><code>100-(nrow(trimmedC12)/nrow(kids12[kids12$acc==1, ]))*100</code></pre>
<pre><code>## [1] 4.639738</code></pre>
<p>4.64% of trials were trimmed from the older child data set.</p>
<pre class="r"><code>trimmedC6 &lt;- kids6[kids6$acc==1, ] %&gt;% group_by(id, relative_hp_dist) %&gt;%
           mutate(sdc = ifelse(length(rt)&gt;=100,2.5,approx(xsize,stds,xout=length(rt))$y), avg = mean(rt), stdev = sd(rt)) %&gt;%
           filter(rt &lt;= sdc*stdev+avg &amp; rt &gt;=avg-(sdc*stdev) &amp; rt &gt;=200 &amp; rt&lt;=18950) %&gt;% #exact upper limit =18929.79
           select(id, age2, relative_hp_dist, rt, block_num2) %&gt;%  #keep these columns in the new data frame
           as.data.frame()


statPrep &lt;- trimmedC6 %&gt;% group_by(id, relative_hp_dist) %&gt;% summarise(measurement=mean(rt)) %&gt;% as.data.frame()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;id&#39;. You can override using the `.groups`
## argument.</code></pre>
<pre class="r"><code>100-(nrow(trimmedC6)/nrow(kids6[kids6$acc==1, ]))*100</code></pre>
<pre><code>## [1] 6.074766</code></pre>
<p>6.07% of trials were trimmed from the younger child data set.</p>
<pre class="r"><code>trimmedC12&lt;- trimmedC12 %&gt;%
  rename(
    block_num=block_num1,
    age=age1
  )

trimmedC6&lt;- trimmedC6 %&gt;%
  rename(
    block_num=block_num2,
    age=age2
  )
kids12&lt;- kids12 %&gt;%
  rename(
    block_num=block_num1,
    age=age1
  )

kids6&lt;- kids6 %&gt;%
  rename(
    block_num=block_num2,
    age=age2
  )</code></pre>
<pre class="r"><code>acc_data &lt;- rbind(adults, kids12)
all_data &lt;- rbind(trimmedA, trimmedC12)</code></pre>
</div>
<div id="examine-accuracy-effects" class="section level3">
<h3>Examine Accuracy Effects</h3>
<pre class="r"><code>acc_data&lt;- acc_data%&gt;%
  filter(id != 26)

acc_data&lt;-acc_data%&gt;%
  mutate(acc=acc*100)</code></pre>
<pre class="r"><code>distacc &lt;- acc_data %&gt;%
  group_by(age,relative_hp_dist) %&gt;%
  summarize(accuracy = mean(acc),
            sd_rt=sd(acc),
            n_rt=32,
            se=sd_rt/sqrt(n_rt),
            upper_limit=accuracy+se,
            lower_limit=accuracy-se
            )</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;age&#39;. You can override using the `.groups`
## argument.</code></pre>
<pre class="r"><code>space &lt;- acc_data %&gt;%
  group_by(age, id, relative_hp_dist) %&gt;%
  summarize(acc = mean(acc)
            )</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;age&#39;, &#39;id&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>space_anova &lt;- setDT(space)
space_anova &lt;- dcast(space_anova,id+age~relative_hp_dist,value.var=&#39;acc&#39;)

space_anova &lt;- space_anova %&gt;%
  mutate(low_prob = (lp_1+lp_2+lp_3)/3)

df_mod &lt;- subset(space_anova, select=c(id, age, high_prob, absent, low_prob))
df_mod &lt;- reshape2::melt(df_mod, id.var=c(&#39;id&#39;, &#39;age&#39;), variable.name= &quot;relative_hp_dist&quot;)</code></pre>
<pre class="r"><code>ggplot(df_mod, aes(relative_hp_dist, value, fill=relative_hp_dist)) +
  geom_bar(stat=&quot;summary&quot;, position=&quot;dodge&quot;) + 
  facet_grid(.~age) +
  xlab(&quot;Distractor Location&quot;) + ylab(&quot;Accuracy (%)&quot;) +
  scale_fill_brewer(palette=&quot;Dark2&quot;) +
  theme(legend.position=&quot;none&quot;)+
  coord_cartesian(ylim = c(85,105))</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`
## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="p09_files/figure-html/plot-first-1.png" width="672" /></p>
<p>Run the 3x2 ANOVA on accuracy data.</p>
<pre class="r"><code>model3 &lt;- aov_car(value ~ age*relative_hp_dist + Error(id/relative_hp_dist), data=df_mod)</code></pre>
<pre><code>## Converting to factor: age</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: age</code></pre>
<pre class="r"><code>model3</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: value
##                 Effect          df   MSE       F  ges p.value
## 1                  age       1, 30 46.83 9.42 ** .206    .005
## 2     relative_hp_dist 1.64, 49.07  6.12  5.42 * .031    .011
## 3 age:relative_hp_dist 1.64, 49.07  6.12    0.46 .003    .596
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1
## 
## Sphericity correction method: GG</code></pre>
<p>Main effect of age is significant – Main effect of distractor
location is significant – interaction is not significant.</p>
<p>Since the interaction was not significant, we’ll exclude age and test
the distractor location effect on accuracy across the 5 conditions.</p>
<pre class="r"><code>model4 &lt;- aov_car(acc ~ relative_hp_dist + Error(id/relative_hp_dist), data=acc_data)</code></pre>
<pre><code>## Warning: More than one observation per design cell, aggregating data using `fun_aggregate = mean`.
## To turn off this warning, pass `fun_aggregate = mean` explicitly.</code></pre>
<pre class="r"><code>model4</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: acc
##             Effect          df   MSE      F  ges p.value
## 1 relative_hp_dist 2.37, 73.41 25.99 3.03 * .032    .046
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1
## 
## Sphericity correction method: GG</code></pre>
<p>Accuracy is different across all locations.</p>
<pre class="r"><code>ggplot(acc_data, aes(relative_hp_dist, acc, fill=relative_hp_dist)) +
  geom_bar(stat=&quot;summary&quot;, position=&quot;dodge&quot;) + 
  facet_grid(.~age) +
  xlab(&quot;Distractor Location&quot;) + ylab(&quot;Response Times (ms)&quot;) +
  scale_fill_brewer(palette=&quot;Dark2&quot;) +
  theme(legend.position=&quot;none&quot;)+
  coord_cartesian(ylim = c(85,105))</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`
## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="p09_files/figure-html/plot-first5-1.png" width="672" /></p>
<p>For the 3 locations (HP, LP, and absent), run t-tests.</p>
<pre class="r"><code>space_anova %&gt;%
  t.test(x=space_anova$low_prob, y=space_anova$high_prob, alternative=&quot;less&quot;, mu=0,paired = TRUE, conf.level = .95) </code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  space_anova$low_prob and space_anova$high_prob
## t = -1.7892, df = 31, p-value = 0.04168
## alternative hypothesis: true mean difference is less than 0
## 95 percent confidence interval:
##         -Inf -0.04780453
## sample estimates:
## mean difference 
##      -0.9128781</code></pre>
<pre class="r"><code>space_anova%&gt;%
  t.test(x=space_anova$high_prob, y=space_anova$absent, alternative=&quot;less&quot;, mu=0, paired =TRUE, conf.level = .95) </code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  space_anova$high_prob and space_anova$absent
## t = -3.2767, df = 31, p-value = 0.001295
## alternative hypothesis: true mean difference is less than 0
## 95 percent confidence interval:
##        -Inf -0.7384317
## sample estimates:
## mean difference 
##       -1.530258</code></pre>
<pre class="r"><code>space_anova%&gt;%
  t.test(x=space_anova$low_prob, y=space_anova$absent, alternative=&quot;less&quot;, mu=0, paired =TRUE, conf.level = .95)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  space_anova$low_prob and space_anova$absent
## t = -3.6668, df = 31, p-value = 0.0004568
## alternative hypothesis: true mean difference is less than 0
## 95 percent confidence interval:
##       -Inf -1.313422
## sample estimates:
## mean difference 
##       -2.443136</code></pre>
<pre class="r"><code>ggplot(df_mod, aes(relative_hp_dist, value, fill=relative_hp_dist)) +
  geom_bar(stat=&quot;summary&quot;, position=&quot;dodge&quot;) +
  xlab(&quot;Distractor Location&quot;) + ylab(&quot;Response Times (ms)&quot;) +
  scale_fill_brewer(palette=&quot;Dark2&quot;) +
  theme(legend.position=&quot;none&quot;)+
  coord_cartesian(ylim = c(85,105))</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="p09_files/figure-html/plot-collapse-1.png" width="672" /></p>
<pre class="r"><code>spaceT &lt;- acc_data %&gt;%
  group_by(age, id, relative_target) %&gt;%
  summarize(acc = mean(acc)
            )</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;age&#39;, &#39;id&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>space_anovaT &lt;- setDT(spaceT)
space_anovaT &lt;- dcast(space_anovaT,id+age~relative_target,value.var=&#39;acc&#39;)

space_anovaT &lt;- space_anovaT %&gt;%
  mutate(low_prob = (lp_1+lp_2+lp_3)/3)

df_mod_targ &lt;- subset(space_anovaT, select=c(id, age, high_prob, low_prob))
df_mod_targ &lt;- reshape2::melt(df_mod_targ, id.var=c(&#39;id&#39;, &#39;age&#39;), variable.name= &quot;relative_target&quot;)</code></pre>
<pre class="r"><code>ggplot(df_mod_targ, aes(relative_target, value, fill=relative_target)) +
  geom_bar(stat=&quot;summary&quot;, position=&quot;dodge&quot;) + 
  facet_grid(.~age) +
  xlab(&quot;Distractor Location&quot;) + ylab(&quot;Accuracy (%)&quot;) +
  scale_fill_brewer(palette=&quot;Dark2&quot;) +
  theme(legend.position=&quot;none&quot;)+
  coord_cartesian(ylim = c(85,105))</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`
## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="p09_files/figure-html/plot-first-target-1.png" width="672" /></p>
<p>Run the 3x2 ANOVA on accuracy data.</p>
<pre class="r"><code>model3 &lt;- aov_car(value ~ age*relative_target + Error(id/relative_target), data=df_mod_targ)</code></pre>
<pre><code>## Converting to factor: age</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: age</code></pre>
<pre class="r"><code>model3</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: value
##                Effect    df   MSE       F   ges p.value
## 1                 age 1, 30 28.93 7.92 **  .194    .009
## 2     relative_target 1, 30  2.80    0.28 &lt;.001    .603
## 3 age:relative_target 1, 30  2.80    0.66  .002    .422
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>For target location accuracy, there is only a main effect of age.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
